### ISSUE TITLE
Expose Constants for pre-defined Resthub Spring profiles

### ISSUE THREAD

**Issue by MarneusCalgarXP** [resthub/resthub-spring-stack#139]
Expose public String Constants for pre-defined Resthub Spring profiles.

**Comment by sdeleuze** [comment]
Not sure this is needed, any advice from other contributors ?

**Comment by bmeurant** [comment]
String constants could not be self-sufficient anyway because of their main use is in application context xml files. So we will have to maintain constants and specific documentation for xml. Maybe this could even be more difficult for IDEs (such Idea) to verify profile definition ...

@MarneusCalgarXP : do you have a specific need for that ? Couldn't this be handled by documentation improvement ?

**Comment by MarneusCalgarXP** [comment]
It's just to avoid mis-spelling in java files, as values will be repeated in many source files. 
Using constants allow to let the java compiler identify errors, and may avoid many headache at runtime to know why parts of the app don't work as expected...

**Comment by bclozel** [comment]
I can see how frustrating this can be. But archetypes and documentation are here. I'm not in favor of adding complexity for this.

@MarneusCalgarXP what kind of error message did you have? Bean instantiation exceptions?
