### ISSUE TITLE
Change datasource class?

### ISSUE THREAD

**Issue by bclozel** [resthub/resthub-spring-stack#155]
Should we switch from apache commonds DBCP to apache tomcat dbcp? We're currently using `org.apache.commons.dbcp.BasicDataSource`.

``` xml
<dependency>
    <groupId>org.apache.tomcat</groupId>
    <artifactId>dbcp</artifactId>
    <version>6.0.36</version>
</dependency>
```

See [this article](https://people.apache.org/~fhanik/jdbc-pool/jdbc-pool.html) for reference.

**Comment by sdeleuze** [comment]
Should be great to have the advice of Romain and/or Jean Louis about that, could you check with them ?
Also we should ensure that it works under Jetty.

**Comment by sdeleuze** [comment]
Interesting thread on stackoverflow : http://stackoverflow.com/questions/4711943/tomcat-dbcp-vs-commons-dbcp

**Comment by bclozel** [comment]
/summon @rmannibucau
What do you think about that Romain?

**Comment by rmannibucau** [comment]
tomcat-dbcp == commons-dbcp (that's a shade)
tomcat-jdbc == fork for higher availability apps

t-jdbc is a bit faster and has some nice features (thanks to interceptor model)

That's said you are in a spring stack so you should maybe consider bonecp which is as interesting as tomcat-jdbc

Side note: it supposes you don't use JTA features of dbcp otherwise you'd need to reimplement it but i guess that's fine in your context

**Comment by bclozel** [comment]
Great advice.
So we should consider bonecp (nice performances, [see benchmark](http://jolbox.com/dynamic-benchmark.html)) or tomcat-jdbc (very interesting features, you mentioned [interceptors](http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport)).

**Comment by bclozel** [comment]
I've got a little experiment that I will contribute with a PR.
Problem is: using bonecp changes things, because it's using different concepts for pool management. So it implies `database.properties` changes for existing applications.
