### ISSUE TITLE
Convert file format from dos to unix.

### ISSUE THREAD

**Issue by loicfrering** [resthub/resthub-spring-stack#78]
We should have unix EOL instead of ^M. If everyone agree, I can convert all the files.

**Comment by bclozel** [comment]
For Netbeans users, once all ^M are turned into EOL, everything should be good because NB detects which line separator it should use with [the first line separator in the current file](http://wiki.netbeans.org/FaqEditorEOLs).

For Eclipse, [it looks like it's an IDE settting](http://stackoverflow.com/questions/5501521/how-to-config-eol-in-eclipse).

**Comment by bmeurant** [comment]
+1. This is true for all resthub repositories

**Comment by bclozel** [comment]
Aaaaaand, we've got to come to a clear "default configuration" for our .gitconfig regarding this issue.

**Comment by bclozel** [comment]
I've found a neat netbeans plugins to [show and change line endings](http://plugins.netbeans.org/plugin/36810/show-and-change-line-endings).

**Comment by bclozel** [comment]
Fixed by 3e4666a
