### ISSUE TITLE
Deploy to Maven central repository

### ISSUE THREAD

**Issue by sdeleuze** [resthub/resthub-spring-stack#82]

**Comment by bclozel** [comment]
Ready to work on this!
See [this issue](https://github.com/resthub/springmvc-router/issues/4) for some details.

**Comment by bclozel** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/resthub/
2.0-SNAPSHOT published on sonatype.

**Comment by bclozel** [comment]
Looks like maven-releasing a project with windows, git, github, gpg is not the easiest task.
The following links explain how to achieve this:
- http://www.theroundmeatball.com/making-maven-release-plugin-on-windows-with-git-gpg-and-github-to-work/
- http://www.sonatype.com/people/2009/09/maven-tips-and-tricks-using-github/

So you have to use a SSH connection to git@github.com, because maven-release-plugin can't display password prompts. Basically, the [Sonatype user guide](https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-7a.1.POMandsettingsconfig) says so for svn.

Doing so behind a company web proxy is a pretty bad idea, especially if it caches 404 HTTP responses, thus preventing you from properly pushing artifacts on a remote nexus. Also, you need to be allowed port 22 on a remote host, otherwise you won't be able to use the git@github connection.

Fun times.

**Comment by sdeleuze** [comment]
Ouch ! Perhaps we should stay with the semi manual mvn versions:set and not mvn release in order to at least just use github http connection ?

**Comment by bclozel** [comment]
Probably. But we'd have to **manually** sign ([oh boy](https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-7b.StageExistingArtifacts)) and deploy artifacts (easy with the web interface).

**Comment by bclozel** [comment]
It is actually doable manually:
- release with versions-maven-plugin
- commit, tag and push
- create and sign artifacts (one-liner)
- create a JAR bundle containing all these artifacts (one-liner)
- manually upload using Sonatype web interface

**Comment by bclozel** [comment]
The full automatic maven-release works with a bit of extra configuration.
